---
- hosts: all
  remote_user: root
  tasks:
    - name: Check for ansible updates in yum systems
      yum: update_cache=yes list=ansible
      register: output
    
    - name: Show result
      debug: var=output
